### ISSUE TITLE
Löschen Funktion

### ISSUE THREAD

**Issue by ghost** [mallocator/Elasticsearch-HBase-River#1]
Leider funktioniert für mich die löschen Funktion nicht:
- wenn ich irgendetwas auf HBase einfüge, ist es sofort von der River anerkannt, und wird in Elasticsearch indizieren. Kein problem.
- doch wenn ich etwas lösche, sieht die River es gar nicht, und macht als ob die linie noch im Dantenbank ist:

![Terminal Foto Beispiel](https://f.cloud.github.com/assets/3930900/384871/899ae998-a66a-11e2-95ee-983474a89cc6.png)

Mit HBase gibt es eine Option, die erlaubt, die gelöschte linie zu sehen. (In HBase Shell: `scan 'users', { RAW => TRUE }`) aber leider habe ich es nicht in asynchbase gefunden.

Doch bin ich sicher, dass die HTable API es erlaubt (mit `Scan s.setRaw(true);`). Ich habe tsuna (asynchbase lead developer) gefragt, und er hat mich gesagt, dass es wahrscheinlich nur eine API Methode fehlt, aber dass es nicht so schwer sein soll, es zu implementieren.

EDIT:

Ok, jetzt habe dein Code gelesen und endlich verstanden, dass was du bietet ist gar nicht was ich will.

Ich möchte, dass die Indexe automatisch gelöscht werden, wenn die daten im Datenbank gelöscht sind.

Doch was du bietest ist die ganze Indexe zu löschen, um danach alles wieder indexieren zu können.

Sowieso soll es etwas anders machen, wenn ich eine Linie in HBase lösche…

**Comment by mallocator** [comment]
Hi,

please keep the conversation in english if possible, so that other international users can read up on the issue as well.

So if I understood you correctly, what you want is a service that keeps a sync between your HBase and Elasticsearch instances. My implementation currently only looks at entries in the HBase table, that were made after the last import, using the HBase timestamp on a dataset. Does the timestamp get updated when you delete an entry from HBase? (Something to consider, while you're developing on this).

Sorry, if the implementation I have doesn't fit your needs. In any way I've updated it, so that it's a bit more safe to use and no Data get's lost on the way (deleted before it's imported). Maybe someone else will be able to use that.

If you get this working let me know, although I'm reluctant to include anything, where you might have to use a custom patch on a dependency like asynchbase.

**Comment by ghost** [comment]
Hi,

Ok, no problem, English is fine for me too.

So you did understand what I wanted to do, but you might have not
understood is that HBase very rarely _really_ delete something. Actually,
it only sets a "tombstone", which is considered as another row, with the
same key, only without any value. Then, when you perform a scan, HBase
checks whether there is a tombstone or not, and only delivers the
appropriate data.

As the tombstone is (almost) exactly like any other row, it does have a
timestamp which actually indicates when the row was deleted. So when you do
a timerange with the option "raw" enabled, you will see the tombstones.

So what your implementation _could_ do, **if you want to**, is checking
every x seconds if there is something new in the database, with "raw"
enabled, so you see every actions (creation, update, or delete) and you can
modify your index accordingly.

If you do not wish to implement such a functionality, I understand. I am
just trying to tell you what I personally want to do. Although, if you
could give me a few pointers, that would really help ;-)

Have a nice day!

Am Donnerstag, 18. April 2013 schrieb Ravi :

**Comment by mallocator** [comment]
Yeah, I got that about HBase. And I would give you some pointers if I had any, but other than digging through the asynchbase code, I have no clue how to help you right now. Of course the implementation would make sense, but from what I gather from the the response of tsuna is that this needs to be a code change in their library.

The right way to go about this would probably be to suggest a patch to the asynchbase project which enables raw access and then use the new version in the river, but I understand that this is time consuming and tedious.

**Comment by ghost** [comment]
Well, it is what I am currently trying to do. I have been working on
asynchbase code for about three days, actually.

Am Donnerstag, 18. April 2013 schrieb Ravi :

**Comment by mallocator** [comment]
closing this task, since there has not been any change in 4 months
